version: '3.7'
services:
  gatewaydb:
    container_name: gatewaydb
    image: mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_DATABASE=gateway
      - MONGO_INITDB_ROOT_USERNAME=gatewaydb
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - gatewaydb:/home/johnazedo/Documents/Volumes/Gateway

  productdb:
    container_name: productdb
    image: mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_DATABASE=product
      - MONGO_INITDB_ROOT_USERNAME=productdba
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27018:27017"
    volumes:
      - productdb:/home/johnazedo/Documents/Volumes/Product
  
volumes:
  gatewaydb:
  productdb: